In [1]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

import numpy as np

arr = np.arange(6)

print("Array:", arr)

print("Data type:", arr.dtype)

Array: [0 1 2 3 4 5]
Data type: int64


In [5]:
# 2. Given a NumPy array 'arr', check if its data type is float64.
# arr = np.array([1.5, 2.6, 3.7])

import numpy as np

arr = np.array([1.5, 2.6, 3.7])

is_float64 = arr.dtype == np.float64

print("Is the data type float64?", is_float64)

Is the data type float64? True


In [6]:
# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

import numpy as np

arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

print("Array:", arr)
print("Data type:", arr.dtype)

Array: [1.+2.j 3.+4.j 5.+6.j]
Data type: complex128


In [8]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

arr_float32 = arr.astype(np.float32)

print("Original array:", arr)
print("Original data type:", arr.dtype)

print("Converted array:", arr_float32)
print("Converted data type:", arr_float32.dtype)

Original array: [1 2 3 4 5]
Original data type: int64
Converted array: [1. 2. 3. 4. 5.]
Converted data type: float32


In [9]:
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision

import numpy as np

arr = np.array([1.123456789, 2.987654321, 3.141592653], dtype=np.float64)

arr_float32 = arr.astype(np.float32)

print("Original array:", arr)
print("Original data type:", arr.dtype)

print("Converted array:", arr_float32)
print("Converted data type:", arr_float32.dtype)

Original array: [1.12345679 2.98765432 3.14159265]
Original data type: float64
Converted array: [1.1234568 2.9876542 3.1415927]
Converted data type: float32


In [10]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and datatype.

import numpy as np

def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    
    return shape, size, dtype

arr = np.array([[1, 2, 3], [4, 5, 6]])

shape, size, dtype = array_attributes(arr)
print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)

Shape: (2, 3)
Size: 6
Data type: int64


In [11]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

import numpy as np

def array_dimension(arr):
    dimension = arr.ndim
    return dimension

arr = np.array([[1, 2, 3], [4, 5, 6]])

dimension = array_dimension(arr)
print("Dimensionality:", dimension)

Dimensionality: 2


In [12]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

import numpy as np

def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size

arr = np.array([[1, 2, 3], [4, 5, 6]])

item_size, total_size = item_size_info(arr)
print("Item size:", item_size)
print("Total size in bytes:", total_size)

Item size: 8
Total size in bytes: 48


In [13]:
# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

import numpy as np

def array_strides(arr):
    strides = arr.strides
    return strides

arr = np.array([[1, 2, 3], [4, 5, 6]])

strides = array_strides(arr)
print("Strides:", strides)

Strides: (24, 8)


In [14]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

import numpy as np

def shape_stride_relationship(arr):
    shape = arr.shape
    strides = arr.strides
    return shape, strides

arr = np.array([[1, 2, 3], [4, 5, 6]])

shape, strides = shape_stride_relationship(arr)
print("Shape:", shape)
print("Strides:", strides)

Shape: (2, 3)
Strides: (24, 8)


In [15]:
# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

import numpy as np

def create_zeros_array(n):
    zeros_array = np.zeros(n)
    return zeros_array

n = 5
zeros_array = create_zeros_array(n)
print("Zeros array:", zeros_array)

Zeros array: [0. 0. 0. 0. 0.]


In [16]:
# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

import numpy as np

def create_ones_matrix(rows, cols):
    ones_matrix = np.ones((rows, cols))
    return ones_matrix

rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)
print("Ones matrix:\n", ones_matrix)

Ones matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

import numpy as np

def generate_range_array(start, stop, step):
    range_array = np.arange(start, stop, step)
    return range_array

start = 1
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)
print("Range array:", range_array)

Range array: [1 3 5 7 9]


In [18]:
# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

import numpy as np

def generate_linear_space(start, stop, num):
    linear_space_array = np.linspace(start, stop, num)
    return linear_space_array

start = 1.0
stop = 5.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)
print("Linear space array:", linear_space_array)

Linear space array: [1. 2. 3. 4. 5.]


In [19]:
# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

import numpy as np

def create_identity_matrix(n):
    identity_matrix = np.eye(n)
    return identity_matrix

n = 4
identity_matrix = create_identity_matrix(n)
print("Identity matrix:\n", identity_matrix)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.

import numpy as np

def list_to_array(py_list):
    np_array = np.array(py_list)
    return np_array

py_list = [1, 2, 3, 4, 5]
np_array = list_to_array(py_list)
print("NumPy array:", np_array)

NumPy array: [1 2 3 4 5]


In [21]:
# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

import numpy as np

original_array = np.array([[1, 2, 3], [4, 5, 6]])

view_array = original_array.view()

view_array[0, 0] = 99

print("Original array:\n", original_array)
print("View array:\n", view_array)

Original array:
 [[99  2  3]
 [ 4  5  6]]
View array:
 [[99  2  3]
 [ 4  5  6]]


In [41]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    
    concatenated_array = np.concatenate((arr1, arr2), axis=axis)
    return concatenated_array

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

result_axis0 = concatenate_arrays(arr1, arr2, axis=0)
print("Concatenated along axis 0:\n", result_axis0)

result_axis1 = concatenate_arrays(arr1, arr2, axis=1)
print("Concatenated along axis 1:\n", result_axis1)

Concatenated along axis 0:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Concatenated along axis 1:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [23]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
arr2 = np.array([[7, 8], [9, 10]])        # Shape (2, 2)

concatenated_array = np.concatenate((arr1, arr2), axis=1)

print("Concatenated array:\n", concatenated_array)

Concatenated array:
 [[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [43]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

import numpy as np

def vertical_stack(arrays):

    stacked_array = np.vstack(arrays)
    return stacked_array

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

result = vertical_stack([arr1, arr2, arr3])
print("Vertically stacked array:\n", result)

Vertically stacked array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

import numpy as np

def create_range_array(start, stop, step):

    range_array = np.arange(start, stop + step, step)
    return range_array

start = 1
stop = 10
step = 2
range_array = create_range_array(start, stop, step)
print("Range array:", range_array)

Range array: [ 1  3  5  7  9 11]


In [45]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1(inclusive).

import numpy as np

def generate_equally_spaced_array(start, stop, num):

    equally_spaced_array = np.linspace(start, stop, num)
    return equally_spaced_array

start = 0
stop = 1
num = 10
array = generate_equally_spaced_array(start, stop, num)
print("Equally spaced array:", array)

Equally spaced array: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [46]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

import numpy as np

def generate_logarithmic_array(start, stop, num):

    log_array = np.logspace(np.log10(start), np.log10(stop), num)
    return log_array

start = 1
stop = 1000
num = 5
log_array = generate_logarithmic_array(start, stop, num)
print("Logarithmically spaced array:", log_array)

Logarithmically spaced array: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [30]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

import numpy as np
import pandas as pd

np_array = np.random.randint(1, 101, size=(5, 3))

df = pd.DataFrame(np_array, columns=['Column1', 'Column2', 'Column3'])

print("DataFrame:\n", df)

DataFrame:
    Column1  Column2  Column3
0        3        9       70
1       40       91       42
2       89        2       37
3       88       77       36
4       96       49       41


In [47]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

import numpy as np
import pandas as pd

def replace_negative_values(df, column_name):

    if column_name not in df.columns:
        raise ValueError(f"Column '{column_name}' not found in the DataFrame.")
    
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    
    return df

data = {
    'A': [10, -5, 7, -3],
    'B': [20, 15, -30, 40]
}
df = pd.DataFrame(data)

df_modified = replace_negative_values(df, 'A')
print("Modified DataFrame:\n", df_modified)

Modified DataFrame:
     A   B
0  10  20
1   0  15
2   7 -30
3   0  40


In [32]:
# 26. Access the 3rd element from the given NumPy array.
# arr = np.array([10, 20, 30, 40, 50])

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

third_element = arr[2]

print("The 3rd element is:", third_element)

The 3rd element is: 30


In [33]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.
# arr_2d = np.array([[1, 2, 3],
#                   [4, 5, 6],
#                   [7, 8, 9]])


import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

element = arr_2d[1, 2]

print("The element at index (1, 2) is:", element)

The element at index (1, 2) is: 6


In [34]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
# arr = np.array([3, 8, 2, 10, 5, 7])

import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7])

mask = arr > 5

filtered_elements = arr[mask]

print("Elements greater than 5:", filtered_elements)

Elements greater than 5: [ 8 10  7]


In [35]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
# arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

sliced_array = arr[2:6]

print("Elements from index 2 to 5 (inclusive):", sliced_array)

Elements from index 2 to 5 (inclusive): [3 4 5 6]


In [40]:
# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
#arr_2d = np.array([[1, 2, 3],
#                   [4, 5, 6],
#                   [7, 8, 9]])

import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slice the array to extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[0:2, 1:3]

print("Extracted sub-array:\n", sub_array)

Extracted sub-array:
 [[2 3]
 [5 6]]


In [48]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

import numpy as np

def extract_elements(arr_2d, indices):

    row_indices, col_indices = indices[:, 0], indices[:, 1]
    
    extracted_elements = arr_2d[row_indices, col_indices]
    
    return extracted_elements

arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

indices = np.array([[0, 1], [1, 2], [2, 0]])

result = extract_elements(arr_2d, indices)
print("Extracted elements:", result)

Extracted elements: [20 60 70]


In [49]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

import numpy as np

def filter_greater_than(arr, threshold):

    mask = arr > threshold
    
    filtered_array = arr[mask]
    
    return filtered_array

arr = np.array([1, 5, 7, 10, 3, 6])
threshold = 5

result = filter_greater_than(arr, threshold)
print("Filtered array:", result)

Filtered array: [ 7 10  6]


In [54]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

import numpy as np

def extract_3d_elements(arr_3d, row_indices, col_indices, depth_indices):

    if not (len(row_indices) == len(col_indices) == len(depth_indices)):
        raise ValueError("Index arrays must have the same length.")

    extracted_elements = arr_3d[row_indices, col_indices, depth_indices]
    
    return extracted_elements

arr_3d = np.array([[[ 1,  2,  3],
                    [ 4,  5,  6],
                    [ 7,  8,  9]],
                   
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],
                   
                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
depth_indices = np.array([2, 0, 1])

result = extract_3d_elements(arr_3d, row_indices, col_indices, depth_indices)
print("Extracted elements:", result)

Extracted elements: [ 6 16 20]


In [56]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

import numpy as np

def filter_elements(arr, condition1, condition2):

    condition1 = np.asarray(condition1)
    condition2 = np.asarray(condition2)
    
    if arr.shape != condition1.shape or arr.shape != condition2.shape:
        raise ValueError("Conditions must have the same shape as the input array.")
    
    combined_condition = condition1 & condition2
    
    filtered_elements = arr[combined_condition]
    
    return filtered_elements

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

condition1 = arr > 30
condition2 = arr < 70

result = filter_elements(arr, condition1, condition2)
print("Filtered elements:", result)

Filtered elements: [40 50 60]


In [57]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

import numpy as np

def extract_elements_2d(arr_2d, row_indices, col_indices):

    row_indices = np.asarray(row_indices)
    col_indices = np.asarray(col_indices)
    
    if row_indices.shape != col_indices.shape:
        raise ValueError("Row and column index arrays must have the same length.")
    
    extracted_elements = arr_2d[row_indices, col_indices]
    
    return extracted_elements

arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 0, 1])

result = extract_elements_2d(arr_2d, row_indices, col_indices)
print("Extracted elements:", result)

Extracted elements: [30 40 80]


In [58]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

scalar = 5

result = arr + scalar

print("Array after adding scalar value:\n", result)

Array after adding scalar value:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [64]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

import numpy as np

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6, 7],
                 [8, 9, 10, 11],
                 [12, 13, 14, 15]])

arr1_broadcasted = arr1.T.reshape(1, 3)

result = arr2[:, :3] * arr1_broadcasted

print("Result after multiplication:\n", result)

Result after multiplication:
 [[ 4 10 18]
 [ 8 18 30]
 [12 26 42]]


In [66]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

import numpy as np

arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])

arr1_broadcasted = arr1[:, :3]

result = arr2 + arr1_broadcasted

print("Result after addition:\n", result)

Result after addition:
 [[ 11  22  33]
 [ 41  52  63]
 [ 71  82  93]
 [101 112 123]]


In [67]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

import numpy as np

arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[10, 20, 30]])

result = arr1 + arr2

print("Result after addition:\n", result)

Result after addition:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [68]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[10, 20],
                 [30, 40]])

arr2_padded = np.pad(arr2, ((0, 0), (0, 1)), mode='constant', constant_values=0)

result = arr1 * arr2_padded

print("Result after multiplication with padded arr2:\n", result)

Result after multiplication with padded arr2:
 [[ 10  40   0]
 [120 200   0]]


In [69]:
# 41. Calculate column wise mean for the given array:
# arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

column_wise_mean = np.mean(arr, axis=0)

print("Column-wise mean:", column_wise_mean)

Column-wise mean: [2.5 3.5 4.5]


In [70]:
# 42. Find maximum value in each row of the given array:
# arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

max_in_rows = np.max(arr, axis=1)

print("Maximum value in each row:", max_in_rows)

Maximum value in each row: [3 6]


In [71]:
# 43. For the given array, find indices of maximum value in each column.
# arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

indices_of_max = np.argmax(arr, axis=0)

print("Indices of maximum value in each column:", indices_of_max)

Indices of maximum value in each column: [1 1 1]


In [72]:
# 44. For the given array, apply custom function to calculate moving sum along rows.
# arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

def moving_sum(arr, window_size):

    result = []
    
    for row in arr:
        row_moving_sum = np.convolve(row, np.ones(window_size), mode='valid')
        result.append(row_moving_sum)
    
    return np.array(result)

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

window_size = 2

moving_sum_result = moving_sum(arr, window_size)

print("Moving sum along rows:\n", moving_sum_result)

Moving sum along rows:
 [[ 3.  5.]
 [ 9. 11.]]


In [73]:
# 45. In the given array, check if all elements in each column are even.
# arr = np.array([[2, 4, 6], [3, 5, 7]])

import numpy as np

arr = np.array([[2, 4, 6],
                [3, 5, 7]])

is_even = (arr % 2 == 0)

all_even_columns = np.all(is_even, axis=0)

print("Are all elements in each column even?", all_even_columns)

Are all elements in each column even? [False False False]


In [75]:
# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
# original_array = np.array([1, 2, 3, 4, 5, 6])

import numpy as np

original_array = np.array([1, 2, 3, 4, 5, 6])

m, n = 2, 3

reshaped_matrix = original_array.reshape(m, n)

print("Reshaped matrix:\n", reshaped_matrix)

# Desired dimensions
m, n = 3, 2  

reshaped_matrix = original_array.reshape(m, n)

print("Reshaped matrix:\n", reshaped_matrix)

Reshaped matrix:
 [[1 2 3]
 [4 5 6]]
Reshaped matrix:
 [[1 2]
 [3 4]
 [5 6]]


In [76]:
# 47. Create a function that takes a matrix as input and returns the flattened array.
# input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

def flatten_matrix(matrix):

    return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)

print("Flattened array:", flattened_array)

Flattened array: [1 2 3 4 5 6]


In [1]:
# 48. Write a function that concatenates two given arrays along a specified axis.
# array1 = np.array([[1, 2], [3, 4]])
# array2 = np.array([[5, 6], [7, 8]])

import numpy as np

def concatenate_arrays(array1, array2, axis):

    return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

concatenated_axis0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", concatenated_axis0)

concatenated_axis1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 1:\n", concatenated_axis1)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [2]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
# original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

import numpy as np

def split_array(array, num_splits, axis=0):

    return np.array_split(array, num_splits, axis=axis)

original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

split_axis0 = split_array(original_array, num_splits=3, axis=0)
print("Split along axis 0:")
for sub_array in split_axis0:
    print(sub_array)

split_axis1 = split_array(original_array, num_splits=3, axis=1)
print("\nSplit along axis 1:")
for sub_array in split_axis1:
    print(sub_array)

Split along axis 0:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

Split along axis 1:
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


In [3]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.
# original_array = np.array([1, 2, 3, 4, 5])
#indices_to_insert = [2, 4]
#values_to_insert = [10, 11]
#indices_to_delete = [1, 3]

import numpy as np

def modify_array(array, indices_to_insert, values_to_insert, indices_to_delete):

    modified_array = np.insert(array, indices_to_insert, values_to_insert)

    modified_array = np.delete(modified_array, indices_to_delete)
    
    return modified_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result_array = modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Modified array:", result_array)

Modified array: [ 1 10  4 11  5]


In [4]:
# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

import numpy as np

arr1 = np.random.randint(0, 100, size=(3, 3))

arr2 = np.arange(1, 10).reshape(3, 3)

result = arr1 + arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise addition:")
print(result)

arr1:
[[98 52  8]
 [ 4 48 15]
 [76 26 12]]

arr2:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Result of element-wise addition:
[[99 54 11]
 [ 8 53 21]
 [83 34 21]]


In [11]:
# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

import numpy as np

arr1 = np.arange(9, 0, -1).reshape(3, 3)

arr2 = np.arange(1, 10).reshape(3, 3)

result = arr1 - arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise subtraction:")
print(result)

arr1:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

arr2:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Result of element-wise subtraction:
[[ 8  6  4]
 [ 2  0 -2]
 [-4 -6 -8]]


In [15]:
# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

import numpy as np

arr1 = np.random.randint(0, 10, size=(3, 5))

arr2 = np.arange(1, 6)

arr2 = arr2.reshape(1, 5)

result = arr1 * arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise multiplication:")
print(result)

arr1:
[[1 6 4 8 5]
 [2 9 7 1 4]
 [9 5 3 6 4]]

arr2:
[[1 2 3 4 5]]

Result of element-wise multiplication:
[[ 1 12 12 32 25]
 [ 2 18 21  4 20]
 [ 9 10  9 24 20]]


In [17]:
# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

import numpy as np

arr1 = np.arange(2, 11, 2)
arr1 = arr1.reshape(1, 5)


arr2 = np.arange(1, 6)

result = arr1 / arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise division:")
print(result)

arr1:
[[ 2  4  6  8 10]]

arr2:
[1 2 3 4 5]

Result of element-wise division:
[[2. 2. 2. 2. 2.]]


In [19]:
# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

import numpy as np

arr1 = np.arange(1, 6)

arr2 = arr1[::-1]

result = np.power(arr1, arr2)

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise exponentiation:")
print(result)

arr1:
[1 2 3 4 5]

arr2:
[5 4 3 2 1]

Result of element-wise exponentiation:
[ 1 16 27 16  5]


In [20]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
# arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

import numpy as np

def count_substring_occurrences(arr, substring):

    count = np.sum(np.char.find(arr, substring) != -1)
    return count

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
result = count_substring_occurrences(arr, substring)

print(f"Occurrences of '{substring}':", result)

Occurrences of 'hello': 3


In [21]:
# 57. Write a function that extracts uppercase characters from a NumPy array of strings.
# arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
# arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

import numpy as np

def extract_uppercase_characters(arr):
    uppercase_chars = []
    
    for string in arr:

        uppercase_chars.extend([char for char in string if char.isupper()])
    
    return uppercase_chars

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
result = extract_uppercase_characters(arr)

print("Uppercase characters:", result)

Uppercase characters: ['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']


In [22]:
# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
# arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

import numpy as np

def replace_substring(arr, old_substring, new_substring):
    replaced_arr = np.char.replace(arr, old_substring, new_substring)
    return replaced_arr


arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'orange'

result = replace_substring(arr, old_substring, new_substring)

print("Original array:")
print(arr)
print("\nModified array:")
print(result)

Original array:
['apple' 'banana' 'grape' 'pineapple']

Modified array:
['orange' 'banana' 'grape' 'pineorange']


In [23]:
# 59. Write a function that concatenates strings in a NumPy array element-wise.
# arr1 = np.array(['Hello', 'World'])
#arr2 = np.array(['Open', 'AI'])

import numpy as np

def concatenate_strings(arr1, arr2):

    concatenated_arr = np.char.add(arr1, arr2)
    return concatenated_arr

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

result = concatenate_strings(arr1, arr2)

print("Concatenated array:")
print(result)

Concatenated array:
['HelloOpen' 'WorldAI']


In [24]:
# 60. Write a function that finds the length of the longest string in a NumPy array.
# arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
# arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

import numpy as np

def length_of_longest_string(arr):
    lengths = np.char.str_len(arr)
    
    max_length = np.max(lengths)
    return max_length

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

result = length_of_longest_string(arr)

print("Length of the longest string:", result)

Length of the longest string: 9


In [25]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

import numpy as np

dataset = np.random.randint(1, 1001, size=100)

mean = np.mean(dataset)


median = np.median(dataset)

variance = np.var(dataset)

std_dev = np.std(dataset)

print("Dataset:")
print(dataset)
print("\nMean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Dataset:
[277 527 927 193  75  13 318 906 775 657 528 615 132 209 230  45 388 894
 251 125 655 600 209 270 329 680 579  15 590 846 752  44 308 411 481 352
 133 935 688 706 721 723 216 256  97 404 692 882 629 934  24 831 606 869
  91 452 244 800  45   1 890 646 377  69 916 926 254 827 663 438 187 214
  24 405 269 301 943 579  96 147 132 767 997  13 131 807 945 442 876  87
 701 637 827   3 373 894 955 417 211 725]

Mean: 472.96
Median: 440.0
Variance: 95524.6584
Standard Deviation: 309.0706365865253


In [26]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

import numpy as np

dataset = np.random.randint(1, 101, size=50)

percentile_25 = np.percentile(dataset, 25)
percentile_75 = np.percentile(dataset, 75)

print("Dataset:")
print(dataset)
print("\n25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

Dataset:
[ 69  12   5  86  45  45  56  34  51  10  35  42  34  73   8  97  89  84
  62  81  67  93  51  23  85  72  88  39  65  82 100  12  39  66  87  66
  86  96  10  55   4  80  70  91  48  30  22  50  37   8]

25th Percentile: 34.25
75th Percentile: 81.75


In [28]:
# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

import numpy as np

array1 = np.random.rand(50)
array2 = np.random.rand(50)

correlation_matrix = np.corrcoef(array1, array2)

correlation_coefficient = correlation_matrix[0, 1]

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nCorrelation Coefficient between Array 1 and Array 2:", correlation_coefficient)

Array 1:
[0.86440529 0.44314693 0.56327527 0.23516136 0.08175109 0.94787779
 0.05499779 0.90263755 0.40386916 0.76139253 0.97877354 0.913978
 0.7919709  0.44495604 0.82747497 0.34367138 0.96553526 0.87866324
 0.06808026 0.07819706 0.59505452 0.55994232 0.16297507 0.79281358
 0.42060245 0.4721759  0.91630677 0.40907587 0.81970591 0.68902774
 0.03007083 0.41380734 0.02183097 0.17005282 0.51219328 0.36890371
 0.50814663 0.23037591 0.82958091 0.59240139 0.31459139 0.02902199
 0.49279333 0.06112292 0.24966288 0.2739353  0.2121082  0.24853945
 0.6249264  0.90807293]

Array 2:
[0.86172256 0.0180663  0.28339883 0.72602364 0.1588474  0.91077627
 0.55184023 0.40479274 0.19761535 0.61959274 0.67678427 0.96907497
 0.08998282 0.12477163 0.42291122 0.99553775 0.53814722 0.65109369
 0.14847009 0.84327948 0.56714574 0.17051608 0.98135763 0.03317505
 0.32523985 0.29260943 0.83561629 0.56101568 0.12876214 0.75460547
 0.27679526 0.67363174 0.8012525  0.02185951 0.58883019 0.2227648
 0.23789507 0.25494576

In [29]:
# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

import numpy as np

matrix1 = np.array([[1, 2, 3], 
                    [4, 5, 6]])

matrix2 = np.array([[7, 8], 
                    [9, 10], 
                    [11, 12]])

result = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult of matrix multiplication:")
print(result)

Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Result of matrix multiplication:
[[ 58  64]
 [139 154]]


In [30]:
#65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

import numpy as np

data = np.random.randint(10, 1001, size=50)

percentile_10 = np.percentile(data, 10)
median = np.percentile(data, 50)
percentile_90 = np.percentile(data, 90)
first_quartile = np.percentile(data, 25)
third_quartile = np.percentile(data, 75)

print("Data Array:")
print(data)
print("\n10th Percentile:", percentile_10)
print("50th Percentile (Median):", median)
print("90th Percentile:", percentile_90)
print("First Quartile (25th Percentile):", first_quartile)
print("Third Quartile (75th Percentile):", third_quartile)

Data Array:
[756 690 834 990 964 521 390 420 906 167 657  58 747  11 279 787 192 522
 378 378 466 364 933 335 956 871 296 429 279  53 612 909 887 399 468 908
 170 595 846 872 236 334 135 107 598 917  16 185  25  21]

10th Percentile: 57.5
50th Percentile (Median): 447.5
90th Percentile: 909.8
First Quartile (25th Percentile): 246.75
Third Quartile (75th Percentile): 822.25


In [31]:
# 66. Create a NumPy array of integers and find the index of a specific element.

import numpy as np

array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

element_to_find = 50

indices = np.where(array == element_to_find)

index_list = indices[0].tolist()

print("Array:")
print(array)
print(f"Element to find: {element_to_find}")
print(f"Index of the element: {index_list}")

Array:
[ 10  20  30  40  50  60  70  80  90 100]
Element to find: 50
Index of the element: [4]


In [32]:
# 67. Generate a random NumPy array and sort it in ascending order.

import numpy as np

random_array = np.random.randint(1, 100, size=20)

sorted_array = np.sort(random_array)

print("Original Array:")
print(random_array)
print("\nSorted Array in Ascending Order:")
print(sorted_array)

Original Array:
[42 18 19 83 45 87  5  5 52 73 58  4  7 80 43  9 96 15 50  1]

Sorted Array in Ascending Order:
[ 1  4  5  5  7  9 15 18 19 42 43 45 50 52 58 73 80 83 87 96]


In [33]:
# 68. Filter elements >20  in the given NumPy array.
# arr = np.array([12, 25, 6, 42, 8, 30])

import numpy as np

arr = np.array([12, 25, 6, 42, 8, 30])

filtered_arr = arr[arr > 20]

print("Original Array:")
print(arr)
print("\nFiltered Array (elements > 20):")
print(filtered_arr)

Original Array:
[12 25  6 42  8 30]

Filtered Array (elements > 20):
[25 42 30]


In [34]:
# 69. Filter elements which are divisible by 3 from a given NumPy array.
# arr = np.array([1, 5, 8, 12, 15])

import numpy as np

arr = np.array([1, 5, 8, 12, 15])

filtered_arr = arr[arr % 3 == 0]

print("Original Array:")
print(arr)
print("\nFiltered Array (elements divisible by 3):")
print(filtered_arr)

Original Array:
[ 1  5  8 12 15]

Filtered Array (elements divisible by 3):
[12 15]


In [35]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
# arr = np.array([10, 20, 30, 40, 50])

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

filtered_arr = arr[(arr >= 20) & (arr <= 40)]

print("Original Array:")
print(arr)
print("\nFiltered Array (20 ≤ elements ≤ 40):")
print(filtered_arr)

Original Array:
[10 20 30 40 50]

Filtered Array (20 ≤ elements ≤ 40):
[20 30 40]


In [40]:
# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
# arr = np.array([1, 2, 3])

import numpy as np

arr = np.array([1, 2, 3])

byte_order = arr.dtype.byteorder

print("Array:")
print(arr)
print("\nByte order of the array:")
print(byte_order)

Array:
[1 2 3]

Byte order of the array:
=


In [43]:
# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
# arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

print("Original Array:")
print(arr)
print("Original Byte Order:")
print(arr.dtype.byteorder)

arr.byteswap(inplace=True)

print("\nArray After Byte Swapping:")
print(arr)
print("Byte Order After Swapping:")
print(arr.dtype.byteorder)

Original Array:
[1 2 3]
Original Byte Order:
=

Array After Byte Swapping:
[16777216 33554432 50331648]
Byte Order After Swapping:
=


In [45]:
# 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
# arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

print("Original Array:")
print(arr)
print("Original Byte Order:")
print(arr.dtype.byteorder)

swapped_arr = arr.newbyteorder()

print("\nArray with Swapped Byte Order:")
print(swapped_arr)
print("Byte Order of New Array:")
print(swapped_arr.dtype.byteorder)

Original Array:
[1 2 3]
Original Byte Order:
=

Array with Swapped Byte Order:
[16777216 33554432 50331648]
Byte Order of New Array:
>


In [46]:
# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
# arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np
import sys

arr = np.array([1, 2, 3], dtype=np.int32)

system_endianness = sys.byteorder

array_byteorder = arr.dtype.byteorder

print("Original Array:")
print(arr)
print("System Endianness:", system_endianness)
print("Array Byte Order:", array_byteorder)

if (system_endianness == 'little' and array_byteorder == '>') or (system_endianness == 'big' and array_byteorder == '<'):
    swapped_arr = arr.newbyteorder()
else:
    swapped_arr = arr

print("\nArray After Conditional Byte Swapping:")
print(swapped_arr)
print("Byte Order of New Array:")
print(swapped_arr.dtype.byteorder)

Original Array:
[1 2 3]
System Endianness: little
Array Byte Order: =

Array After Conditional Byte Swapping:
[1 2 3]
Byte Order of New Array:
=


In [48]:
# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
# arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np
import sys

arr = np.array([1, 2, 3], dtype=np.int32)

system_endianness = sys.byteorder

array_byteorder = arr.dtype.byteorder

def needs_byte_swap(system_endianness, array_byteorder):
    if array_byteorder == '=':
        return False
    if system_endianness == 'little' and array_byteorder == '>':
        return True
    if system_endianness == 'big' and array_byteorder == '<':
        return True
    return False

swap_needed = needs_byte_swap(system_endianness, array_byteorder)

print("Original Array:")
print(arr)
print("System Endianness:", system_endianness)
print("Array Byte Order:", array_byteorder)
print("Is byte swapping necessary?", swap_needed)

if swap_needed:
    swapped_arr = arr.newbyteorder()
    print("\nArray After Byte Swapping:")
    print(swapped_arr)
    print("Byte Order of New Array:")
    print(swapped_arr.dtype.byteorder)
else:
    print("\nNo byte swapping needed.")

Original Array:
[1 2 3]
System Endianness: little
Array Byte Order: =
Is byte swapping necessary? False

No byte swapping needed.


In [49]:
# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

import numpy as np

arr1 = np.arange(1, 11)

copy_arr = arr1.copy()

copy_arr[5] = 99

print("Original Array (arr1):")
print(arr1)
print("\nModified Copy (copy_arr):")
print(copy_arr)

print("\nHas arr1 been affected by modifying copy_arr?")
print(np.array_equal(arr1, copy_arr))

Original Array (arr1):
[ 1  2  3  4  5  6  7  8  9 10]

Modified Copy (copy_arr):
[ 1  2  3  4  5 99  7  8  9 10]

Has arr1 been affected by modifying copy_arr?
False


In [50]:
# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

import numpy as np

matrix = np.random.randint(1, 10, size=(3, 3))

view_slice = matrix[1:, 1:]

print("Original Matrix:")
print(matrix)
print("\nView Slice:")
print(view_slice)

view_slice[0, 0] = 99

print("\nModified View Slice:")
print(view_slice)
print("\nOriginal Matrix After Modifying View Slice:")
print(matrix)

Original Matrix:
[[1 8 6]
 [1 9 4]
 [6 2 7]]

View Slice:
[[9 4]
 [2 7]]

Modified View Slice:
[[99  4]
 [ 2  7]]

Original Matrix After Modifying View Slice:
[[ 1  8  6]
 [ 1 99  4]
 [ 6  2  7]]


In [52]:
# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

import numpy as np

array_a = np.arange(1, 13).reshape(4, 3)

view_b = array_a[1:, 1:]

print("Original Array (array_a):")
print(array_a)
print("\nView Slice (view_b):")
print(view_b)

view_b += 5

print("\nModified View Slice (view_b):")
print(view_b)
print("\nOriginal Array After Broadcasting Addition:")
print(array_a)

Original Array (array_a):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

View Slice (view_b):
[[ 5  6]
 [ 8  9]
 [11 12]]

Modified View Slice (view_b):
[[10 11]
 [13 14]
 [16 17]]

Original Array After Broadcasting Addition:
[[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 16 17]]


In [54]:
# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

import numpy as np

orig_array = np.arange(1, 9).reshape(2, 4)

reshaped_view = orig_array.reshape(4, 2)

print("Original Array (orig_array):")
print(orig_array)
print("\nReshaped View (reshaped_view):")
print(reshaped_view)

reshaped_view[2, 1] = 99

print("\nModified Reshaped View (reshaped_view):")
print(reshaped_view)
print("\nOriginal Array After Modification:")
print(orig_array)

Original Array (orig_array):
[[1 2 3 4]
 [5 6 7 8]]

Reshaped View (reshaped_view):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Modified Reshaped View (reshaped_view):
[[ 1  2]
 [ 3  4]
 [ 5 99]
 [ 7  8]]

Original Array After Modification:
[[ 1  2  3  4]
 [ 5 99  7  8]]


In [55]:
# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

import numpy as np

np.random.seed(0)
data = np.random.randint(1, 10, size=(3, 4))

data_copy = data[data > 5].copy()


print("Original Data (data):")
print(data)
print("\nCopy of Elements Greater Than 5 (data_copy):")
print(data_copy)

data_copy[0] = 99

print("\nModified Copy (data_copy):")
print(data_copy)
print("\nOriginal Data After Modification:")
print(data)

Original Data (data):
[[6 1 4 4]
 [8 4 6 3]
 [5 8 7 9]]

Copy of Elements Greater Than 5 (data_copy):
[6 8 6 8 7 9]

Modified Copy (data_copy):
[99  8  6  8  7  9]

Original Data After Modification:
[[6 1 4 4]
 [8 4 6 3]
 [5 8 7 9]]


In [57]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

addition_result = A + B

subtraction_result = A - B

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nAddition Result (A + B):")
print(addition_result)
print("\nSubtraction Result (A - B):")
print(subtraction_result)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition Result (A + B):
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction Result (A - B):
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [58]:
# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

import numpy as np

C = np.random.randint(1, 10, size=(3, 2))

D = np.random.randint(1, 10, size=(2, 4))


result = C @ D

print("Matrix C (3x2):")
print(C)
print("\nMatrix D (2x4):")
print(D)
print("\nMatrix Multiplication Result (C @ D):")
print(result)

Matrix C (3x2):
[[9 2]
 [7 8]
 [8 9]]

Matrix D (2x4):
[[2 6 9 5]
 [4 1 4 6]]

Matrix Multiplication Result (C @ D):
[[ 26  56  89  57]
 [ 46  50  95  83]
 [ 52  57 108  94]]


In [59]:
# 83. Create a matrix `E` and find its transpose.

import numpy as np

E = np.random.randint(1, 10, size=(3, 4))

E_transpose = E.T

print("Original Matrix (E):")
print(E)
print("\nTranspose of Matrix (E^T):")
print(E_transpose)

Original Matrix (E):
[[1 3 4 9]
 [2 4 4 4]
 [8 1 2 1]]

Transpose of Matrix (E^T):
[[1 2 8]
 [3 4 1]
 [4 4 2]
 [9 4 1]]


In [60]:
# 84. Generate a square matrix `F` and compute its determinant.

import numpy as np

# Generate a square matrix F of shape (3, 3) with random integers
F = np.random.randint(1, 10, size=(3, 3))

# Compute the determinant of matrix F
determinant_F = np.linalg.det(F)

# Print the matrix and its determinant
print("Matrix F (3x3):")
print(F)
print("\nDeterminant of Matrix F:")
print(determinant_F)

Matrix F (3x3):
[[5 8 4]
 [3 8 3]
 [1 1 5]]

Determinant of Matrix F:
68.99999999999996


In [61]:
# 85. Create a square matrix `G` and find its inverse.

import numpy as np

# Generate a square matrix G of shape (3, 3) with random integers
G = np.random.randint(1, 10, size=(3, 3))

# Compute the determinant to check if the matrix is invertible
determinant_G = np.linalg.det(G)

if determinant_G != 0:
    # Compute the inverse of matrix G
    G_inverse = np.linalg.inv(G)
    
    # Print the matrix and its inverse
    print("Matrix G (3x3):")
    print(G)
    print("\nInverse of Matrix G:")
    print(G_inverse)
else:
    print("Matrix G is singular and does not have an inverse.")

Matrix G (3x3):
[[6 6 7]
 [9 5 2]
 [5 9 2]]

Inverse of Matrix G:
[[-0.02702703  0.1722973  -0.0777027 ]
 [-0.02702703 -0.0777027   0.1722973 ]
 [ 0.18918919 -0.08108108 -0.08108108]]
